### ISSUE TITLE
Dark Mode: Can't see active filters

### ISSUE THREAD

**Issue by jsjoeio** [jsjoeio/joeprevite.com#170]
It's really hard to tell which filters are active on the /articles page when using the site in dark mode

**Comment by javila35** [comment]
You have a color commented out on [line 48](https://github.com/jsjoeio/joeprevite.com/blob/1ccb3d0021232ed93fae4689c9a65edffc7cabd5/src/components/Theming.js#L48). I added that after trying a few other colors, and I think it looks good. Plus it's consistent with the color you use in default. It seems like you didn't like that color as an option since it's commented out. Am I right in assuming you want something else, or can I go ahead and push that with your comment added? 🤪

**Comment by jsjoeio** [comment]
Ah! I don't know what I was thinking. You're right though. That color does look good. 

@javila35 I think if you want to go ahead and use that, I would totally accept that. You are so awesome for commenting on this and even considering fixing it for me! 🙌🏼 🙏🏼

**Comment by jsjoeio** [comment]
Fixed by #203
