### ISSUE TITLE
Site doesn't work in Russia

### ISSUE THREAD

**Issue by jsjoeio** [jsjoeio/joeprevite.com#32]
**Describe the bug**
The site doesn't work in Russia.

**To Reproduce**

1. Use a VPN or something to make it look like I'm in Russia??
2. Visit joeprevite.com

**Expected behavior**
The site should work in Russia.

**Screenshots**
![image](https://user-images.githubusercontent.com/3806031/71382112-b6789f00-2593-11ea-97a6-e8abdf1793ec.png)

**Additional context**
Found by @talentlessguy

**Comment by v1rtl** [comment]
Hello, I'm the one who sent it on twitter

# Cause of the problem
Because of frequent blocks of RKN organization a lot of Netlify websites are being unavailable.

# Background
I contacted a person who works at Netlify and he said that servers are being transfered to Yandex Cloud if I'm not wrong. But some websites still don't work.

# Solution

Deploy a mirror on [Zeit Now](https://now.sh) or any other platform. Now has an [example for Gatsby](https://github.com/zeit/now-examples/tree/master/gatsby) so it won't take much to get started with.

**Comment by jsjoeio** [comment]
Oh perfect! Thanks for the additional context @talentlessguy! I'll see if I can ping a friend at Netlify as well. And if not, I'll try your suggested solution.
